u0o
dl-academy-edu/yo-kitov-samir-3 pull request #3
Opened 2022-12-27 09:21 UTC by rival7774

2022-12-30 11:56 UTC, AlexFGeeR requested changes

2022-12-30 11:56 UTC, AlexFGeeR commented on source/js/common.js
> +  regularPhone = /(\+7|8)[\s(]?(\d{3})[\s)]?(\d{3})[\s-]?(\d{2})[\s-]?(\d{2})/g
Хорошая задумка с точки зрения переиспользования кода в плане того, что программист может внести изменения в регулярку, но нет никакой необходимости в подобном переиспользовании.
Основная причина отсутствия такой необходимости: Валидация нужна для того чтобы пользовательские данные соответствовали ожиданиям сервера. Так как, мы работаем с одним и тем же сервером, ожидания сервера не могут меняться в зависимости от формы. Не может быть такого что в одном моменте сервер принимает номер телефона по маске: 8-9xx-xxx-xx-xx, а потом в какой-то другой момент решает что будет работать с +7-9xx-xxx-xx-xx

2022-12-30 11:56 UTC, AlexFGeeR commented on source/js/common.js
> +  inputs.forEach((input) => {
### Обращаю внимание на потенциальный баг.
Конструкция `[...form.elements]` вёрнет тебе массив с элементами формы, которые в свою очередь являются не только input'ами. Ты же в последствии перебираешь их как инпуты. То есть, если бы не условие `input.hasAttribute('required')` весь код который идет дальше применялся бы и к кнопкам, и даже к fieldset'у. Ты мог это учесть и как раз отталкиваться от этого, но я тебе на всякий случай подсвечиваю этот момент.

2022-12-30 11:56 UTC, AlexFGeeR commented on source/js/form-profile/form-profile.js
> +if (document.querySelector('.profile__info')) {
### Перегрузка.
Когда я увидел это условие, я не понял зачем оно тебе, но потом увидел, что ты все свои js файлы импортируешь в один app.js
Есть два взгляда на подобную организацию кода: 
1) Это перегрузка. По факту, если расширять функционал твоего сайта и добавлять туда новые элементы, то это создаст огромный поток js модулей, которые ты подключаешь к любой странице на сайте и они увеличивают скорость загрузки твоей страницы. Также это можно подкрепить тем, что ты делаешь код переиспользуемым на будущее вне рамок макета ( например, твой подход к регуляркам ), но при этом этим действием ты ставишь под вопрос возможность сильного расширения твоего проекта.
2) То что ты объединяешь всё это в один модуль неплохо и подобный подход используется и во фреймворках, но нужно понимать, что во фреймворках - это работает немного по другому. 
Я не говорю тебе переписывать что-то, просто маркирую моменты.

2022-12-30 11:56 UTC, AlexFGeeR commented on source/js/form-profile/form-profile.js
> +  const wrapButton = document.querySelector('.profile__info');
### Непонятный нейминг
У тебя есть контейнер, который ты кладешь в переменную. Но при этом, переменную с контейнером ты называешь кнопкой. Читаемость кода от этого падает.

2022-12-30 11:56 UTC, AlexFGeeR commented on source/js/form-profile/form-profile.js
> +  const formData = document.querySelector('.editing-data__form');
### Нейминг
Я бы добавил здесь Modal, потому что данные окна являются модальными, но читая текущие названия переменных, я не понимаю что в них лежит: контейнер, форма, пароль или какая-то дата.

2022-12-30 11:56 UTC, AlexFGeeR commented on source/js/form-profile/form-profile.js
> +    }
### Классная идея
Мне нравится подход

2022-12-30 11:56 UTC, AlexFGeeR commented on source/js/form-profile/form-profile.js
> +  const HIDDEN = 'hidden';
### Надобность данной константы.
Не особо понимаю надобность в данной переменной. По сути во всём проекте у тебя один и тот же класс будет использоваться для скрытия элементов, а ты зачем-то добавляешь вариативность и расширяешь параметры функций для того чтобы поддерживать вариативность в том, что не должно быть вариативно, ведь класс `hidden` как раз делается для переиспользования в кейсах по скрытым элементам.

2023-01-04 13:56 UTC, AlexFGeeR requested changes

2023-01-04 13:56 UTC, AlexFGeeR commented on source/js/forms/utils-form.js
> +}
### Переиспользование
Ты можешь объединить эту функцию и часть фукнции `removeErrorMessages()` где происходит удаление маркировки с инпутов в одну функцию.
Есть два варианта как это сделать: добавить аргумент type и сделать case со значениями `correct` `error` в зависимости от которого будет удаляться либо error, либо correct. Либо ты можешь передавать сами классы инпутов и класс ошибки или успешного заполнения поля.

2023-01-04 13:56 UTC, AlexFGeeR commented on source/js/forms/utils-form.js
> +}
### Оптимизация. 
В принципе ты можешь добавить preLoader в верстку изначально, нежели постоянно его создавать и удалять.

2023-01-06 22:02 UTC, rival7774 commented on source/js/forms/utils-form.js
> +}
Тогда его придется добавлять на каждую страницу, а так получается универсальнее

2023-01-06 22:05 UTC, rival7774 commented on source/js/forms/utils-form.js
> +}
я думал об этом но решил придерживаться принципа, что функция должна отвечать за одно действие

2023-01-27 07:55 UTC, merged